version: '3.8'

services:
  # SQL Server Database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: graphicrequest-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SERVER_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "${SQL_SERVER_PORT:-1433}:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - graphicrequest-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SQL_SERVER_PASSWORD} -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  # Backend API
  api:
    build:
      context: ./GraphicRequestSystem.API
      dockerfile: Dockerfile
    container_name: graphicrequest-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=${DATABASE_NAME:-GraphicRequestDb};User Id=sa;Password=${SQL_SERVER_PASSWORD};TrustServerCertificate=true;
      - Jwt__Issuer=${JWT_ISSUER:-http://localhost:5000}
      - Jwt__Audience=${JWT_AUDIENCE:-http://localhost:5000}
      - Jwt__Key=${JWT_KEY}
    ports:
      - "${API_PORT:-5000}:80"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - graphicrequest-network
    volumes:
      - api-uploads:/app/wwwroot/uploads
    restart: unless-stopped

  # Frontend Client
  client:
    build:
      context: ./graphic-request-client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5000/api
    container_name: graphicrequest-client
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - graphicrequest-network
    restart: unless-stopped

volumes:
  sqlserver-data:
    driver: local
  api-uploads:
    driver: local

networks:
  graphicrequest-network:
    driver: bridge
