// <auto-generated />
using System;
using GraphicRequestSystem.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphicRequestSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250926180113_RefactorRequestTypeToLookup")]
    partial class RefactorRequestTypeToLookup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphicRequestSystem.API.Core.Entities.Lookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Lookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "RequestTypes"
                        });
                });

            modelBuilder.Entity("GraphicRequestSystem.API.Core.Entities.LookupItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LookupId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LookupId");

                    b.ToTable("LookupItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LookupId = 1,
                            Value = "طراحی لیبل"
                        },
                        new
                        {
                            Id = 2,
                            LookupId = 1,
                            Value = "عکس بسته‌بندی محصولات"
                        },
                        new
                        {
                            Id = 3,
                            LookupId = 1,
                            Value = "پست اینستاگرام"
                        },
                        new
                        {
                            Id = 4,
                            LookupId = 1,
                            Value = "ویدئو تبلیغاتی"
                        },
                        new
                        {
                            Id = 5,
                            LookupId = 1,
                            Value = "محتوا برای سایت"
                        },
                        new
                        {
                            Id = 6,
                            LookupId = 1,
                            Value = "ویرایش فایل"
                        },
                        new
                        {
                            Id = 7,
                            LookupId = 1,
                            Value = "کالای تبلیغاتی"
                        },
                        new
                        {
                            Id = 8,
                            LookupId = 1,
                            Value = "تبلیغات بصری"
                        },
                        new
                        {
                            Id = 9,
                            LookupId = 1,
                            Value = "تبلیغات محیطی"
                        },
                        new
                        {
                            Id = 10,
                            LookupId = 1,
                            Value = "متفرقه"
                        });
                });

            modelBuilder.Entity("GraphicRequestSystem.API.Core.Entities.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RequestTypeId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("GraphicRequestSystem.API.Core.Entities.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SettingKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("GraphicRequestSystem.API.Core.Entities.LookupItem", b =>
                {
                    b.HasOne("GraphicRequestSystem.API.Core.Entities.Lookup", "Lookup")
                        .WithMany()
                        .HasForeignKey("LookupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lookup");
                });

            modelBuilder.Entity("GraphicRequestSystem.API.Core.Entities.Request", b =>
                {
                    b.HasOne("GraphicRequestSystem.API.Core.Entities.LookupItem", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestType");
                });
#pragma warning restore 612, 618
        }
    }
}
